# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mayfly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mayfly)

$(call add-radio-file-sha1-checked,radio/abl.img,89b2b87caf0698c34a68bd69726ea52b97d987ec)
$(call add-radio-file-sha1-checked,radio/aop.img,893b1c3ea5f84b6ab70b1f178ccc7473240b0fb0)
$(call add-radio-file-sha1-checked,radio/aop_config.img,b2fc8b033ce9f87605b36ccb354e06ff72fccfd5)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,ae1a0fe0da55a44731b9af573fc2cb6b3211feb5)
$(call add-radio-file-sha1-checked,radio/cpucp.img,14160fb249fbd501872793eae330a5774c35c36a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a054d3316b7f6a2f30ca256e0f55093a811ad12e)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,3b6c165c9495c731a02d1cd95cead48e0a3956f9)
$(call add-radio-file-sha1-checked,radio/hyp.img,cde45e0d787b2f4e094959717216d62ab3f96001)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e3c8922d68466ace2e4cba997221bdd8d2edace0)
$(call add-radio-file-sha1-checked,radio/keymaster.img,45da6f981380115b111d9b0b290a125db9ddceda)
$(call add-radio-file-sha1-checked,radio/modem.img,484017d0fd5e3454fb09e68a86fed48f2c913cc3)
$(call add-radio-file-sha1-checked,radio/qupfw.img,9b7bc1d6f5dbd1b53a8714a1c0b31bc5efdc7b81)
$(call add-radio-file-sha1-checked,radio/shrm.img,11d9e91bfad81398381b2251e4f4e5e6efc97c7f)
$(call add-radio-file-sha1-checked,radio/tz.img,a6cff2630f5f2232fac624b0b78a0223f51202ad)
$(call add-radio-file-sha1-checked,radio/uefi.img,2cf4b0b5d71b5d6310f3211a9399d8f0b50ad9a2)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,ec489802a1a88845dc27e21efe6e8a065138dab2)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,65956965276f1b16fe8983c9712962dcd3ee5d0f)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,04af90949590539a11ca253c46985b8ad8ba4c30)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,0c10ad772911491d78737484f6685a3953ae8870)

endif
