# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mayfly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mayfly)

$(call add-radio-file-sha1-checked,radio/abl.img,149cc9c622f92be807f67479487848cde9e77c93)
$(call add-radio-file-sha1-checked,radio/aop.img,24eda8be86e34948c7c5798503626c7cf7e962d3)
$(call add-radio-file-sha1-checked,radio/aop_config.img,30415f9c63ecb40da79c72dac8aed7b139b4b2dc)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b0a7099fc186c652b3455e461095c2b87a8d081e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,82287dcab4b875f8daabba09c8b45354e6a1ea6e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,64bf6b303a5f9dfa6bdd9c6efcf784d54ee8751d)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,99a50468b17b030415efd9436d63172871a01964)
$(call add-radio-file-sha1-checked,radio/hyp.img,d01fb5395d17c4266eeef948fcd659097739a4ee)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e62f0f42f9fdb26ca400bbcc42a0a7ff333b8b50)
$(call add-radio-file-sha1-checked,radio/keymaster.img,034138a2512af96fcf58742eb503e329c3cfa11d)
$(call add-radio-file-sha1-checked,radio/modem.img,7c55f6cd6b31111be4823cce09c57906f6d54fb0)
$(call add-radio-file-sha1-checked,radio/qupfw.img,caa0872f7654481c4d4149973fbbb3d35d1cc25a)
$(call add-radio-file-sha1-checked,radio/shrm.img,2de85d8f480e705b54a42543631e53fe540845a9)
$(call add-radio-file-sha1-checked,radio/tz.img,0a51c57b82db3e5d980a07a94f5d0be0dfec60a7)
$(call add-radio-file-sha1-checked,radio/uefi.img,226101ddf185216eb635b1bbc0f56a6d5cb6dac6)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c5deed4f749dafb4572e0160c6ddb50cd9ec5555)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,b1bb6e5f6324c1f72a89fb26f2f160c779d2092b)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,28ba3389331cf1870d7f54c33f7706909c0b32f7)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,bd1070ab1b36033b1de9cf8ee98ccdc12a2d702d)

endif
