# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mayfly/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    aop_config \
    bluetooth \
    cpucp \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    qupfw \
    shrm \
    tz \
    uefi \
    uefisecapp \
    vm-bootsys \
    xbl \
    xbl_config \
    xbl_ramdump
